<?php


/**
* @file
* Functions to support theming in the themename theme.
*/

use Drupal\Core\Form\FormBase;

use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\user\Entity\User;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render;
use \Drupal\node\Entity\Node;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpKernel\Profiler;
use Drupal\field_collection\Entity\FieldCollectionItem;
use Drupal\Core\Routing;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Controller\ControllerBase;
use Symfony\Component\HttpFoundation\Request;
use \Drupal\views\ViewExecutable;


function frams_pro_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /*kint($form_id);*/
  $form_ids = ['user_frc_form', 'user_promoter_form','user_claimant_form','user_teo_form'];
  $node_form_id = ['node_application_archives_form','node_application_claimant_form','node_teo_form'];
  if (in_array($form_id, $form_ids) ) {

    $node_id = \Drupal::request()->query->get('nid');
    $form_display = $form_state->getStorage()['form_display']->getMode();

    switch ($form_display) {
      case 'claimant':
        $curr_time = \Drupal::time()->getCurrentTime();
        $form['account']['mail']['#access'] = FALSE;
        $form['account']['name']['#access'] = FALSE;
        $form['account']['name']['#default_value'] = $curr_time;
        $form['account']['mail']['#default_value'] = $curr_time . '-claimant@frams.com';
        $form['actions']['submit']['#submit']   = array_merge(
          ['claimant_user_register_submit'],
            $form['actions']['submit']['#submit']
          );
        $form['#validate']   = array_merge(
          ['claimant_user_register_validate'],
            $form['#validate']
          );
        $form['actions']['submit']['#value'] = t('Sign Up');

      break;
      case 'frc':
        $node_frc = Node::load($node_id);
        if(!empty($node_frc)) {
          $teo = $node_frc->get('field_frc_teo')->entity;
          $district = $node_frc->get('field_frc_district')->entity;
          $panchayat = $node_frc->get('field_frc_panchayat')->entity;
          /*kint($node_frc->get('field_frc_email')->get('0')->getValue());*/
          $email = $node_frc->get('field_frc_email')->get('0')->getValue();
          $name = explode(' ', $node_frc->getTitle());

          $form['frc_profiles']['widget']['0']['entity']['field_district']['widget']['0']['target_id']['#default_value'] = $district;
          $form['frc_profiles']['widget']['0']['entity']['field_grama_panchayat']['widget']['0']['target_id']['#default_value'] = $panchayat;
          $form['frc_profiles']['widget']['0']['entity']['field_profile_frc']['widget']['0']['target_id']['#default_value'] = $node_frc;
          $form['account']['name']['#default_value'] = 'frc@'. strtolower($name[count($name)-1]);
          $form['account']['mail']['#default_value'] = $email;
          $form['actions']['submit']['#submit']   = array_merge(
            ['_user_register_submit'],
            $form['actions']['submit']['#submit']
          );
          /*$form['#validate']   = array_merge(
            ['claimant_user_register_validate'],
            $form['#validate']
          );*/
          $form['actions']['submit']['#value'] = t('Sign Up');
        }
        break;
        case 'promoter':
          $node_promoter = Node::load($node_id);
          if(!empty($node_promoter)) {
            $teo = $node_promoter->get('field_teo')->entity;
            $name = explode(' ', $node_promoter->getTitle());
            $email = $node_promoter->get('field_email')->get('0')->getValue();
            $form['promoter_profiles']['widget']['0']['entity']['field_profile_promoter']['widget']['0']['target_id']['#default_value'] = $node_promoter;
            $form['promoter_profiles']['widget']['0']['entity']['field_teo']['widget']['0']['target_id']['#default_value'] = $teo;
            $form['account']['name']['#default_value'] = 'pro@'. strtolower($name[0]);
            $form['account']['mail']['#default_value'] = $email;
            $form['actions']['submit']['#submit']   = array_merge(
              ['_user_register_submit'],
              $form['actions']['submit']['#submit']
            );
            $form['actions']['submit']['#value'] = t('Sign Up');
        }
        break;
        case 'teo':
          $node_teo = Node::load($node_id);
          if(!empty($node_teo)) {
            $tdo = $node_teo ->get('field_tdo')->entity;
            $name = explode(' ', $node_teo->getTitle());
            $email = $node_teo->get('field_teo_email')->get('0')->getValue();
            $form['teo_profiles']['widget']['0']['entity']['field_profile_teo']['widget']['0']['target_id']['#default_value'] = $node_teo;
            $form['teo_profiles']['widget']['0']['entity']['field_tdo']['widget']['0']['target_id']['#default_value'] = $tdo;
            $form['account']['name']['#default_value'] = 'teo@'. strtolower($name[count($name)-1]);
            $form['account']['mail']['#default_value'] = $email;
            $form['actions']['submit']['#submit']   = array_merge(
              ['_user_register_submit'],
              $form['actions']['submit']['#submit']
            );
            $form['actions']['submit']['#value'] = t('Sign Up');
        }
        break;

      default:

    }
  }
  switch ($form_id) {
    case 'node_application_archives_form':
      $form['field_archives']['widget']['value']['#default_value'] = TRUE;
      if (array_key_exists('moderation_state', $form) ) {

        /*$node = $form_state->getFormObject()->getEntity();
        $moderationState = $node->get('moderation_state')->getValue('state');
        if (isset($moderationState[0]['value'])) {

        }*/
        $form['moderation_state']['widget'][0]['state']['#default_value'] = 'ror_issued';
      }
    break;
    case 'node_teo_form':
      $current_user_roles = \Drupal::currentUser()->getRoles();
      if (in_array('tdo', $current_user_roles)) {
        $user = User::load(\Drupal::currentUser()->id());
        $tdo_profile = \Drupal::entityTypeManager()
          ->getStorage('profile')
          ->loadByProperties([
            'uid' => $user->id(),
            'type' => 'tdo',
          ]);
        if (!empty($tdo_profile)) {
          $tdo_value = array_shift(array_values($tdo_profile));
          $tdo = $tdo_value->get('field_profile_tdo')->entity;
          $form['field_tdo']['widget'][0]['target_id']['#default_value'] = $tdo;
        }
      }
    break;
    case 'node_application_claimant_form':
    // kint($form);
      $user = User::load(\Drupal::currentUser()->id());

      $claimant_profile = \Drupal::entityTypeManager()
        ->getStorage('profile')
        ->loadByProperties([
          'uid' => $user->id(),
          'type' => 'claimant',
        ]);
     /*   kint($claimant_profile);*/
      if (!empty($claimant_profile)) {
        $claimant = array_shift(array_values($claimant_profile));
        $name = isset($name) && !empty($name) ? $name : ''; $user->realname;
        $aadhar_no = isset($claimant->field_claimant_aadhar_number->value) && !empty($claimant->field_claimant_aadhar_number->value) ? $claimant->field_claimant_aadhar_number->value : '';
        $contact_no = isset($claimant->field_user_claimant_phone_number->value) && !empty($claimant->field_user_claimant_phone_number->value) ? $claimant->field_user_claimant_phone_number->value : '';
        $district = isset($claimant->get('field_district')->entity) && !empty($claimant->get('field_district')->entity) ? $claimant->get('field_district')->entity : '';
        $frc = isset($claimant->get('field_frc')->entity) && !empty($claimant->get('field_frc')->entity) ? $claimant->get('field_frc')->entity : '';
        $grama_panchayat = isset($claimant->get('field_grama_panchayat')->entity) && !empty($claimant->get('field_grama_panchayat')->entity) ? $claimant->get('field_grama_panchayat')->entity : '';
        $settlement = isset($claimant->get('field_settlement')->entity) && !empty($claimant->get('field_settlement')->entity) ? $claimant->get('field_settlement')->entity : '';
        $sdlc = isset($frc->get('field_frc_sdlc')->entity) && !empty($frc->get('field_frc_sdlc')->entity) ? $frc->get('field_frc_sdlc')->entity : '';
        $dlc = isset($sdlc->get('field_dlc')->entity) && !empty($sdlc->get('field_dlc')->entity) ? $sdlc->get('field_dlc')->entity : '';
        $slc = isset($dlc->get('field_slc')->entity) && !empty($dlc->get('field_slc')->entity) ? $dlc->get('field_slc')->entity : '';

        $village = isset($frc->get('field_frc_village')->entity) && !empty($frc->get('field_frc_village')->entity) ? $frc->get('field_frc_village')->entity : '';
        $taluk = isset($village->get('field_taluk')->entity) && !empty($village->get('field_taluk')->entity) ? $village->get('field_taluk')->entity : '';
        $constituency = isset($frc->get('field_frc_constituency')->entity) && !empty($frc->get('field_frc_constituency')->entity) ? $frc->get('field_frc_constituency')->entity : '';
        $range = isset($frc->get('field_frc_forest_range')->entity) && !empty($frc->get('field_frc_forest_range')->entity) ? $frc->get('field_frc_forest_range')->entity : '';
        $teo = isset($frc->get('field_frc_teo')->entity) && !empty($frc->get('field_frc_teo')->entity) ? $frc->get('field_frc_teo')->entity : '';
        $tdo = isset($teo->get('field_tdo')->entity) && !empty($teo->get('field_tdo')->entity) ? $teo->get('field_tdo')->entity : '';;
        $promoter = isset($frc->get('field_frc_promoter')->entity) && !empty($frc->get('field_frc_promoter')->entity) ? $frc->get('field_frc_promoter')->entity : '';

        $form['title']['widget'][0]['value']['#default_value'] = isset($name) && !empty($name) ? $name : '';
        $form['field_adharcard_no']['widget'][0]['value']['#default_value'] = isset($aadhar_no) && !empty($aadhar_no) ? $aadhar_no : '';
        $form['field_contact_no']['widget'][0]['value']['#default_value'] =  isset($contact_no) && !empty($contact_no) ? $contact_no : '';
        $form['field_claimant_district']['widget'][0]['target_id']['#default_value'] =  isset($district) && !empty($district) ? $district : '';
        $form['field_claimant_frc']['widget'][0]['target_id']['#default_value'] =  isset($frc) && !empty($frc) ? $frc : '';
        $form['field_claimant_panchayat']['widget'][0]['target_id']['#default_value'] =  isset($grama_panchayat) && !empty($grama_panchayat) ? $grama_panchayat : '';
        $form['field_claimant_settlement']['widget'][0]['target_id']['#default_value'] =  isset($settlement) && !empty($settlement) ? $settlement : '';
        $form['field_claimant_sdlc']['widget'][0]['target_id']['#default_value'] =  isset($sdlc) && !empty($sdlc) ? $sdlc : '';
        $form['field_claimant_dlc']['widget'][0]['target_id']['#default_value'] =  isset($dlc) && !empty($dlc) ? $dlc : '';
        $form['field_claimant_slc']['widget'][0]['target_id']['#default_value'] =  isset($slc) && !empty($slc) ? $slc : '';
        $form['field_claimant_village']['widget'][0]['target_id']['#default_value'] =  isset($village) && !empty($village) ? $village : '';
        $form['field__claimant_taluk']['widget'][0]['target_id']['#default_value'] =  isset($taluk) && !empty($taluk) ? $taluk : '';
        $form['field_claimant_constituency']['widget'][0]['target_id']['#default_value'] =  isset($constituency) && !empty($constituency) ? $constituency : '';
        $form['field__claimant_range']['widget'][0]['target_id']['#default_value'] =  isset($range) && !empty($range) ? $range : '';
        $form['field_claimant_teo']['widget'][0]['target_id']['#default_value'] =  isset($teo) && !empty($teo) ? $teo : '';
        $form['field_claimant_tdo']['widget'][0]['target_id']['#default_value'] =  isset($tdo) && !empty($tdo) ? $tdo : '';
        $form['field_claimant_promoter']['widget'][0]['target_id']['#default_value'] =  isset($promoter) && !empty($promoter) ? $promoter : '';
        $form['revision']['#access'] = FALSE;
        $form['revision_log']['#access'] = FALSE;
        $form['revision_information']['#access'] = FALSE;
      }
    break;
    case 'views_form_dashboard_applications_dash_frc_new':
      $form['#action'] = '';
    break;

    default:
  }
   if ($form_id == 'node_frc_form' || $form_id = 'node_promoters_form') {
    $current_user_roles = \Drupal::currentUser()->getRoles();
    if (in_array('teo', $current_user_roles)) {
      $user = User::load(\Drupal::currentUser()->id());
      $teo_profile = \Drupal::entityTypeManager()
        ->getStorage('profile')
        ->loadByProperties([
          'uid' => $user->id(),
          'type' => 'teo',
        ]);
      if (!empty($teo_profile)) {
        $teo_value = array_shift(array_values($teo_profile));
        $teo = $teo_value->get('field_profile_teo')->entity;
        $form['field_frc_teo']['widget'][0]['target_id']['#default_value'] = $teo;
        $form['field_teo']['widget'][0]['target_id']['#default_value'] = $teo;
      }
    }
  }
}
function claimant_user_register_validate(&$form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  $aadhar = $values['claimant_profiles'][0]['entity']['field_claimant_aadhar_number'][0]['value'];
  $valid = _isAadharValid($aadhar);
  if (!empty($aadhar) && _isAadharValid($aadhar)) {
    $form_state->setValue('name', $aadhar);
    $form_state->setValue('mail', $aadhar . '@frams.com');
  }
  else {
    $form_state->setErrorByName('claimant_profiles', t('Aadhar number is not valid.'));
  }
}

/**
 * Custom submit handler for user registration.
 */
function claimant_user_register_submit(&$form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  $_REQUEST['destination'] = '/node/add/application/claimant';
  // $response = new RedirectResponse('node/add/application/claimant');
  // $response->send();
  // $form_state->setRedirect('node.add',['node_type' => 'application']);
  // $dest_url = "/node/add/application/claimant";
  // $url = Url::fromUri('internal:' . $dest_url);
  // $form_state->setRedirect($url);
}
/**
 * Custom submit handler for user registration.
 */
function _user_register_submit(&$form, FormStateInterface $form_state) {
  $form_display = $form_state->getStorage()['form_display']->getMode();
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $current_user = \Drupal::currentUser();
  $roles = $current_user->getRoles();
  switch ($form_display) {
    case 'frc':
      $form_state->setValue('roles', ['frc']);
      break;
    case 'promoter':
      $form_state->setValue('roles', ['promoter']);
      break;
      case 'teo':
      $form_state->setValue('roles', ['teo']);
      break;
    default:
  }
}

function frams_pro_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if (!empty($fields['field_claimant_aadhar_number'])) {
    $current_path = \Drupal::service('path.current')->getPath();
    if ($current_path == '/claimant/register') {
      // $fields['field_claimant_aadhar_number']->addConstraint('AadharValid');
    }
  }
}
/**
 * Implements hook_entity_presave().
 */
function frams_pro_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityType()->id() == 'node') {
    switch ($entity->bundle()) {
      case 'application':
        if($entity->get('moderation_state')->value == 'ror_issued') {
          $entity->set('field_ror_issued', TRUE);
        }
       break;
    }
  }
}
/**
 * Implements hook_theme().
 */
function frams_pro_theme($existing, $type, $theme, $path) {
  return [
    'individual_hab' => [
      'variables' => ['ind_hab_data' => [],
     ],
    ],
    'individual_cul' => [
      'variables' => ['ind_cul_data' => [],
     ],
    ],
    'individual' => [
      'variables' => ['ind_data' => [],
     ],
    ],
  ];
}


/**
 * Custom function check Aadhar card No.
 */

function _isAadharValid($num) {
  settype($num, "string");
  $expectedDigit = substr($num, -1);
  $actualDigit = CheckSumAadharDigit(substr($num, 0, -1));
  return ($expectedDigit == $actualDigit) ? $expectedDigit == $actualDigit : 0;
}

function CheckSumAadharDigit($partial) {
  $dihedral = array(
    array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
    array(1, 2, 3, 4, 0, 6, 7, 8, 9, 5),
    array(2, 3, 4, 0, 1, 7, 8, 9, 5, 6),
    array(3, 4, 0, 1, 2, 8, 9, 5, 6, 7),
    array(4, 0, 1, 2, 3, 9, 5, 6, 7, 8),
    array(5, 9, 8, 7, 6, 0, 4, 3, 2, 1),
    array(6, 5, 9, 8, 7, 1, 0, 4, 3, 2),
    array(7, 6, 5, 9, 8, 2, 1, 0, 4, 3),
    array(8, 7, 6, 5, 9, 3, 2, 1, 0, 4),
    array(9, 8, 7, 6, 5, 4, 3, 2, 1, 0)
  );
  $permutation = array(
    array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
    array(1, 5, 7, 6, 2, 8, 3, 0, 9, 4),
    array(5, 8, 0, 3, 7, 9, 6, 1, 4, 2),
    array(8, 9, 1, 6, 0, 4, 3, 5, 2, 7),
    array(9, 4, 5, 3, 1, 2, 6, 8, 7, 0),
    array(4, 2, 8, 6, 5, 7, 3, 9, 0, 1),
    array(2, 7, 9, 3, 8, 0, 6, 4, 1, 5),
    array(7, 0, 4, 6, 9, 1, 3, 2, 5, 8)
  );

  $inverse = array(0, 4, 3, 2, 1, 5, 6, 7, 8, 9);
  settype($partial, "string");
  $partial = strrev($partial);
  $digitIndex = 0;
  for ($i = 0; $i < strlen($partial); $i++) {
      $digitIndex = $dihedral[$digitIndex][$permutation[($i + 1) % 8][$partial[$i]]];
  }
  return $inverse[$digitIndex];
}
