# Schema for the configuration files of the loading bar library module.
loading_bar_library.loading_bar_style.*:
  type: config_entity
  label: 'Loading bar style'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: string
      label: 'Label'
    description:
      type: string
      label: 'Description'
    configuration:
      type: mapping
      label: 'Configuration'
      mapping:
        preset:
          type: string
          label: 'Preset'
        type:
          type: string
          label: 'Progress type'
        fill-dir:
          type: string
          label: 'Fill type direction'
        stroke-dir:
          type: string
          label: 'Stroke type direction'
        img:
          type: string
          label: 'Image of fill type'
        path:
          type: string
          label: 'SVG Path command'
        fill:
          type: string
          label: 'Fill type'
        fill-background:
          type: string
          label: 'Fill color of the background'
        fill-background-extrude:
          type: string
          label: 'Size of the background shape'
        stroke:
          type: string
          label: 'Stroke type'
        stroke-width:
          type: string
          label: 'Stroke width'
        stroke-linecap:
          type: string
          label: 'Stroke linecap'
        stroke-trail:
          type: string
          label: 'Trail color'
        stroke-trail-width:
          type: string
          label: 'Trail width'
        pattern-size:
          type: string
          label: 'Pattern size'
        img-size:
          type: string
          label: 'Image size'
        min:
          type: string
          label: 'Minimum value'
        max:
          type: string
          label: 'Maximum value'
        label:
          type: string
          label: 'Label'
        width:
          type: string
          label: 'Width'
        height:
          type: string
          label: 'Height'
