# Schema for the configuration files of the mail entity queue module.

mail_entity_queue.mail_entity_queue.*:
  type: config_entity
  label: 'Mail entity queue'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: string
      label: 'Label'
    cron_delay:
      type: integer
      label: 'Delay between items'
    cron_items:
      type: integer
      label: 'Number of items'
    format:
      type: string
      label: 'Format'
    queue_processor:
      type: string
      label: 'Plugin'
